modLoader="kotlinforforge"
loaderVersion="[3,)"
license="Creative Commons Attribution-NonCommercial-NoDerivatives 4.0"
issueTrackerURL="https://github.com/ManApart/jump-pads/issues"

[[mods]]
    modId="jumppads"
    version="1.0"
    displayName="Jump Pads"
	authors="ManApart"
    description='''
    Jumppads!
    '''
    credits="Jumppads!"

[[dependencies.jumppads]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"